name: 'GitHub Actions '

on:
  push:
    branches: 
      - main
  schedule:
   - cron: '0 14 * * *'
jobs:
  ddy:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      # - name: Checkout
      #   uses: actions/checkout@v2
      # - name: 'Set up Python'
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: 3.8
      # - name: 'Install dependencies'
      #   run: python -m pip install --upgrade pip
      # - name: 'Install requirements'
      #   run: pip install -r ./requirements.txt
      - name: 'Working'
        timeout-minutes: 360
        run: |
          chmod +x ./iptest.sh
          bash ./iptest.sh
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "⌚️$(date +%Y%m%d%H%M%S)" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          # github_token: ${{ secrets.GH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}